# Generated by Django 3.2.9 on 2021-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhsentry',
            name='sd',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=3),
        ),
    ]
