# Generated by Django 3.2.9 on 2021-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhs', '0002_hhsentry_sd'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhsentry',
            name='player',
            field=models.CharField(default='wolfmuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='hhsentry',
            name='cr',
            field=models.DecimalField(decimal_places=1, default=72.0, max_digits=3, verbose_name='CR'),
        ),
        migrations.AlterField(
            model_name='hhsentry',
            name='sd',
            field=models.DecimalField(decimal_places=1, default=10, editable=False, max_digits=3),
        ),
    ]
