# Generated by Django 3.2.9 on 2021-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhs', '0004_remove_hhsentry_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhsentry',
            name='player',
            field=models.CharField(default='wolfmuel', max_length=20),
        ),
    ]
